### ISSUE TITLE
Must register plugin after models?

### ISSUE THREAD

**Issue by jocull** [kripod/bookshelf-validate#6]
I received a strange error about `this.collections` being undefined when I attempted to register the `bookshelf-validate` plugin before registering my models. The error did not surface until calling into `fetch` / `fetchAll`.

Do you know why? It took me awhile to figure out that the order of registration seems to matter. Thanks!

**Comment by kripod** [comment]
Sorry, but I'm not sure about the reason, and have dropped support for this project of mine.

**Comment by jocull** [comment]
Ok, thanks for the response, kripod. What are you using in its place?

**Comment by kripod** [comment]
I would recommend using [Objection.js](http://vincit.github.io/objection.js/) instead of Bookshelf. It has some great modern coding principles implemented.
